<?php
/**
 * Copyright © 2017 Dxvn, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper            = $this->helper( 'Magento\Catalog\Helper\Output' );
$_mode              = $block->getMode();
$_mode              = 'grid';
?>
<?php if ( ! $_productCollection->count() ): ?>
    <div class="message info empty">
        <div><?= __( 'We can\'t find products matching the selection.' ) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ( $_mode == 'grid' ) {
        $viewMode        = 'grid';
        $image           = 'category_page_grid';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode        = 'list';
        $image           = 'category_page_list';
        $showDescription = false;
        $templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= $viewMode; ?> products-<?= $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ( $_productCollection as $_product ): ?>
                <?= ( $iterator ++ == 1 ) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage( $_product, $image );
                    if ( $pos != null ) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags( $_product->getName(), null, true );
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $_product->getProductUrl() ?>">
                                <?= $_helper->productAttribute( $_product, $_product->getName(), 'name' ); ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml( $_product, $templateType ); ?>
                        <?= $block->getProductPrice( $_product ) ?>
                        <?= $block->getProductDetailsHtml( $_product ); ?>
                    </div>
                </div>
                <?= ( $iterator == count( $_productCollection ) + 1 ) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php if ( ! $block->isRedirectToCartEnabled() ) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }










        </script>
    <?php endif; ?>
<?php endif; ?>
