<?php
/**
 * Copyright © 2017 Dxvn, Inc. All rights reserved.
 */

/**
 * Template for displaying grouped product price
 */
?>
<?php
$product    = null;
$finalPrice = $block->getSaleableItem()
                    ->getPriceInfo()
                    ->getPrice( \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE );

if ( method_exists( $finalPrice, 'getMaxProduct' ) ) {
    $product = $finalPrice->getMaxProduct();
} else {
    $product = $finalPrice->getMinProduct();
}

if ( $product ) {
    $amountRender = $block->getRendererPool()->createAmountRender(
        $product->getPriceInfo()->getPrice( 'final_price' )->getAmount(),
        $product,
        $product->getPriceInfo()->getPrice( 'final_price' ),
        [ 'include_container' => true ]
    );
}
?>
<div class="price-box">
    <?php if ( $product && \Magento\Framework\Pricing\Render::ZONE_ITEM_VIEW != $block->getZone() ) : ?>
        <p class="minimal-price">
            <?= $amountRender->toHtml() ?>
        </p>
    <?php endif ?>
</div>
